SELECT r1.FOOD_TYPE, r1.REST_ID, r1.REST_NAME, r1.FAVORITES
    FROM REST_INFO AS r1
        WHERE (r1.FOOD_TYPE, r1.FAVORITES) IN
        (SELECT r2.FOOD_TYPE, MAX(r2.FAVORITES)
            FROM REST_INFO AS r2
                GROUP BY r2.FOOD_TYPE)
            ORDER BY r1.FOOD_TYPE DESC;