SELECT ao.ANIMAL_ID, ao.ANIMAL_TYPE, ao.NAME
FROM ANIMAL_OUTS ao
WHERE EXISTS (
    SELECT 1
    FROM ANIMAL_INS ai
    WHERE ai.ANIMAL_ID = ao.ANIMAL_ID
    AND ai.SEX_UPON_INTAKE LIKE 'Intact%'
)
AND (ao.SEX_UPON_OUTCOME LIKE 'Spayed%' OR ao.SEX_UPON_OUTCOME LIKE 'Neutered%')
ORDER BY ao.ANIMAL_ID ASC;