SELECT fp.PRODUCT_ID, fp.PRODUCT_NAME, SUM(fo.AMOUNT * fp.PRICE) AS TOTAL_SALES
    FROM FOOD_ORDER fo
        JOIN FOOD_PRODUCT fp
            ON fo.PRODUCT_ID = fp.PRODUCT_ID
        WHERE fo.PRODUCE_DATE BETWEEN '2022-05-01' AND '2022-05-31'
            GROUP BY fp.PRODUCT_ID, fp.PRODUCT_NAME
                ORDER BY TOTAL_SALES DESC, fp.PRODUCT_ID ASC;