SELECT MEMBER_ID AS id, MEMBER_NAME AS name, GENDER, DATE_FORMAT(DATE_OF_BIRTH, "%Y-%m-%d")
    FROM MEMBER_PROFILE
        WHERE MONTH(DATE_OF_BIRTH) = 3 AND GENDER = 'W' AND TLNO IS NOT NULL
            ORDER BY id ASC;