SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, 
    (SELECT MAX(SIZE_OF_COLONY)
     FROM ECOLI_DATA
     WHERE YEAR(DIFFERENTIATION_DATE) = YEAR(ed.DIFFERENTIATION_DATE)) - ed.SIZE_OF_COLONY AS YEAR_DEV,
     ID
        FROM ECOLI_DATA AS ed
            ORDER BY YEAR ASC, YEAR_DEV ASC;
