SELECT gb.TITLE, gb.BOARD_ID, gr.REPLY_ID, gr.WRITER_ID, gr.CONTENTS, gr.CREATED_DATE
FROM USED_GOODS_BOARD AS gb
INNER JOIN USED_GOODS_REPLY AS gr
ON gb.BOARD_ID = gr.BOARD_ID
WHERE gb.CREATED_DATE >= '2022-10-01' AND gb.CREATED_DATE <= '2022-10-31'
ORDER BY gr.CREATED_DATE ASC, gb.TITLE ASC