SELECT fr.CATEGORY, fr.PRICE AS MAX_PRICE, fr.PRODUCT_NAME
FROM FOOD_PRODUCT fr
WHERE fr.CATEGORY IN ('과자', '국', '김치', '식용유')
  AND (fr.CATEGORY, fr.PRICE) IN (
    SELECT CATEGORY, MAX(PRICE)
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
    GROUP BY CATEGORY
  )
ORDER BY fr.PRICE DESC